### PR TITLE
make personal changes.

### PR DESCRIPTION
**Pull request by webbrowser11**
add some stuff

### CODE REVIEW

**Comment by KhangDeveloperd** [comment]
bruh who let u cook?

**Comment by webbrowser11** [comment]
i let myself

**Comment by webbrowser11** [comment]
now are you gonna merge it?

**Comment by webbrowser11** [comment]
merge it!

**Comment by webbrowser11** [comment]
https://github.com/Alter-Net-codes/SkyOS/releases/tag/v2.6.5 also i can test this bad boy now but you could still test them since we are the developing crew and we dont have much time to test

**Comment by webbrowser11** [comment]
bro pls merge why wont u merggggEEE???

**Comment by KhangDeveloperd** [comment]
> merge it!

I'm kinda new to github, but how to merge?

**Comment by webbrowser11** [comment]
click the merge button.

**Comment by webbrowser11** [comment]
or just gimme write acssess for today and i can do it then.

**Comment by webbrowser11** [comment]
dude?

**Comment by KhangDeveloperd** [comment]
> dude?

done

**Comment by webbrowser11** [comment]
done get rid of me.

**Comment by webbrowser11** [comment]
no wait...

**Comment by webbrowser11** [comment]
okay now get rid of me

**Pull request merged**
